### PR TITLE
DO NOT MERGE Problem: need error details

### PR DESCRIPTION
**Pull request by thalman**
Solution: remove --quiet

Signed-off-by: Tomas Halman <TomasHalman@eaton.com>

### CODE REVIEW

**Comment by jimklimov** [comment]
The changeset is bigger than just (almost invisible) removal of `--quiet` and is a bump to an already obsoleted template from zproject.

Idea for the change is good however, posted as a manageable feature to upstream as https://github.com/zeromq/zproject/pull/786

**Comment by thalman** [comment]
DO NOT MERGE!!
This change is not here for merging but to get configure output of ./configure and figure out what is wrong with NUT dependencies.

**Comment by jimklimov** [comment]
@thalman : since you're online, see https://github.com/42ity/fty-nut/pull/3 - the dependency part is now fixed and the fix is merged, but project code needs corrections (bad func signatures called).

**Comment by jimklimov** [comment]
Ok, now that zproject PR is merged, so such experimental toggle would be in travis.yml (after updating this project with upstream templates)

**Comment by jimklimov** [comment]
Thanks to @vyskocilm the remaining issue in PR #3 is now fixed as PR #4 - so travis is green at that point.

**Pull request closed without merging**
