### PR TITLE
Improve performances with new libnutclient method

### PR DESCRIPTION
**Pull request by boricj**
Querying device variables in bulk significantly improves throughput. A test scenario with 300 ePDUs reduced the processing time duration from 15 seconds down to about 1 second.

This depends on a new method in libnutclient (https://github.com/networkupstools/nut/pull/654).

### CODE REVIEW

**Comment by jimklimov** [comment]
LGTM

**Comment by aquette** [comment]
@geraldguillaume, @boricj and @jimklimov this PR will need the mentioned PR (networkupstools/nut#654) to be backported from upstream into our 42ity/nut before succeeding to build

**Comment by jimklimov** [comment]
Re-ran CI builds now that new libnutclient is in our FTY branch and Jenkins workers' OS images.

**Comment by aquette** [comment]
@boricj this will need a backport to 1.5 now that nut is also synced there!

**Pull request merged**
