### PR TITLE
Problem: current Travis tests fail because NUT wants to build docs

### PR DESCRIPTION
**Pull request by jimklimov**
Solution: ci_build.sh : tell NUT to not build docs (it is faster to test than setting up the asciidoc infrastructure)

### CODE REVIEW

**Comment by jimklimov** [comment]
As far as travis part goes, the job seems done - now it fails with poor C/C++ coding of the project itself (probably due to conversions all around), see end of https://travis-ci.org/42ity/fty-nut/builds/188318641 :

````
3257 src/nut.cc: In function ‘int nut_save(nut_t*, const char*)’:
3258 src/nut.cc:442:55: error: too many arguments to function ‘zframe_t* zmsg_encode(zmsg_t*)’
3259         uint64_t size = zmsg_encode (zmessage, &buffer);
3260                                                       ^
3261 In file included from /home/travis/build/42ity/fty-nut/tmp/include/czmq_library.h:154:0,
3262                 from /home/travis/build/42ity/fty-nut/tmp/include/czmq.h:37,
3263                 from /home/travis/build/42ity/fty-nut/tmp/include/mlm_library.h:24,
3264                 from /home/travis/build/42ity/fty-nut/tmp/include/malamute.h:17,
3265                 from src/../include/fty_nut_library.h:33,
3266                 from src/../include/fty_nut.h:26,
3267                 from src/fty_nut_classes.h:33,
3268                 from src/nut.cc:29:
3269 /home/travis/build/42ity/fty-nut/tmp/include/zmsg.h:184:5: note: declared here
3270     zmsg_encode (zmsg_t *self);
3271     ^
3272 src/nut.cc:442:55: error: invalid conversion from ‘zframe_t* {aka _zframe_t*}’ to ‘uint64_t {aka long unsigned int}’ [-fpermissive]
3273         uint64_t size = zmsg_encode (zmessage, &buffer);
3274                                                       ^
3275 src/nut.cc: In function ‘int nut_load(nut_t*, const char*)’:
3276 src/nut.cc:521:63: error: cannot convert ‘byte* {aka unsigned char*}’ to ‘zframe_t* {aka _zframe_t*}’ for argument ‘1’ to ‘zmsg_t* zmsg_decode(zframe_t*)’
3277         zmsg_t *zmessage = zmsg_decode (data, (size_t) *prefix);
3278                                                               ^
3279 make[1]: *** [src/src_libfty_nut_la-nut.lo] Error 1
3280 make[1]: *** Waiting for unfinished jobs....
3281 make[1]: Leaving directory `/home/travis/build/42ity/fty-nut'
3282 make: *** [all-recursive] Error 1
````

**Comment by vyskocilm** [comment]
No, this is because different api in czmq master. See fty-email project.xml on how to require compatible czmq.

**Comment by jimklimov** [comment]
@vyskocilm : thanks, will try

**Comment by jimklimov** [comment]
It worked (and then some more fixes were needed), so it is green now there - thanks :)

**Pull request merged**
